name: Update Dependencies

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update packages in each directory
        run: |
          dirs=("react-lib" "ts-lib" "ts-lib-monorepo")
          for dir in "${dirs[@]}"; do
            echo "Updating dependencies in $dir..."
            cd "$dir"
            bun update
            cd -
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "chore: update dependencies"
            git push
          fi
